---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for ping_host

# Ping an host

- name: "Ping the host {{ host }}"
  shell: "{{ ping_command }} {{ host }}"
  register: command_output
  ignore_errors: yes
  no_log: true
  changed_when: false

- name: Ping Success
  debug:
    msg: "PING SUCCESS"
  when: command_output.rc == 0

