---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0

# tasks file for snmp_config

# Configure SNMP

- name: Replace sysLocation
  become: true
  replace: 
    path: "{{ snmp_config_file }}"
    regexp: '(^sysLocation\s)(.*)$'
    replace: "\\1 {{ sysLocation }}"
    backup: yes
  when: sysLocation is defined

- name: Replace sysContact
  become: true
  replace: 
    path: "{{ snmp_config_file }}"
    regexp: '(^sysContact\s)(.*)$'
    replace: "\\1 {{ sysContact }}"
  when: sysContact is defined

- block:
  - name: Replace agentaddress
    become: true
    replace: 
      path: "{{ snmp_config_file }}"
      regexp: '(^agentaddress\s)(.*)$'
      replace: "\\1 {{ agentaddress | regex_escape() }}"
    register: agentaddress_set 
    when: agentaddress is defined

  - name: Replace agentaddress by default
    become: true
    replace:
      path: "{{ snmp_config_file }}"
      regexp: '(^agentaddress\s)(.*)$'
      replace: "\\1 {{ snmp_default_agentaddress }}"
    when: not (agentaddress is defined)

  #Add community to the new config file:
  #echo “rocommunity [rocommunitydetails]”>/etc/snmp/snmpd.conf
  - name: SNMPD - Add read only community 
    become: true
    ansible.builtin.lineinfile:
      path: '/etc/snmp/snmpd.conf'
      state: present
      line: "rocommunity {{ rocommunitydetails }}"
    when: rocommunitydetails is defined

  - name: SNMPD - Add read only community IPv6
    become: true
    ansible.builtin.lineinfile:
      path: '/etc/snmp/snmpd.conf'
      state: present
      line: "rocommunity6 {{ rocommunitydetails }}"
    when: rocommunitydetails is defined

  #Add community to the new config file:
  #echo “rwcommunity [rwcommunitydetails]”>/etc/snmp/snmpd.conf
  - name: SNMPD - Add read write community 
    become: true
    ansible.builtin.lineinfile:
      path: '/etc/snmp/snmpd.conf'
      state: present
      line: "rwcommunity {{ rwcommunitydetails }}"
    when: rwcommunitydetails is defined

  - name: SNMPD - Add read write community IPv6
    become: true
    ansible.builtin.lineinfile:
      path: '/etc/snmp/snmpd.conf'
      state: present
      line: "rwcommunity6 {{ rwcommunitydetails }}"
    when: rwcommunitydetails is defined

- name: SERVICE - Ensure snmpd service reloaded
  become: true
  service:
    name: snmpd
    state: reloaded


