---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_ssh

# Firewall - SSH rules

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    ufw:
      state: enabled
    register: ufw_started

  - block:
    #sudo ufw allow ssh
    - name: UFW - SSH - ufw allow ssh
      ufw:
        rule: allow
        name: OpenSSH
      when: 'ssh_port|int == 22'

    #sudo ufw allow [ssh_port]
    - name: UFW - SSH - ufw allow [ssh_port] on non standard port
      ufw:
        rule: allow
        port: "{{ ssh_port | int }}"
        proto: tcp
        comment: 'SSH'
      when: 'ssh_port|int != 22'

    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'
