---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_dns_server

# Firewall - rules for DNS Server

# Debian
- block:
  #use ufw

  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    ufw:
      state: enabled
    register: ufw_started

  - block:

    #sudo ufw allow dns
    - name: UFW - DNS Server - ufw allow dns
      ufw:
        rule: allow
        port: '53'
        comment: DNS

    #sudo ufw allow 953
    - name: UFW - DNS Server - ufw allow 953
      ufw:
        rule: allow
        port: '953'
        proto: any
        comment: DNS
    
    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'
