---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_dhcp_server

# Firewall - DHCP Server rules

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    ufw:
      state: enabled
    register: ufw_started

  - block:
    #sudo ufw allow 67
    - name: UFW - DHCP - ufw allow 67
      ufw:
        rule: allow
        port: '67'
        proto: udp
        comment: 'DHCP Server'
      when: ipv4|bool is true

    #sudo ufw allow 547
    - name: UFW - DHCPv6 - ufw allow 547
      ufw:
        rule: allow
        port: '547'
        proto: udp
        comment: 'DHCPv6 Server'
      when: ipv6|bool is true

    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'
