---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_dhcp_server

# Firewall - DHCP Server rules

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    become: true
    ufw:
      state: enabled
    register: ufw_started

  - block:
    #sudo ufw allow 67
    - name: UFW - DHCP - ufw allow 67
      become: true
      ufw:
        rule: allow
        port: '67'
        proto: udp
        comment: 'DHCP Server'
      when: ipv4|bool is true

    #sudo ufw allow 547
    - name: UFW - DHCPv6 - ufw allow 547
      become: true
      ufw:
        rule: allow
        port: '547'
        proto: udp
        comment: 'DHCPv6 Server'
      when: ipv6|bool is true

    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'

# RedHat
- block:
  #use firewalld

  - block:
    - name: Firewalld - DHCP Server
      become: true
      ansible.posix.firewalld:
        service: dhcp
        permanent: true
        state: enabled
      when: ipv4|bool is true

  - block:
    - name: Firewalld - DHCP Server
      become: true
      ansible.posix.firewalld:
        service: dhcpv6
        permanent: true
        state: enabled
      when: ipv6|bool is true

  - block:
    #allow 67/udp
    - name: FIREWALLD - DHCP Server - allow 67/udp
      become: true
      ansible.posix.firewalld:
        port: "67/udp"
        permanent: true
        state: enabled
      when: ipv4|bool is true

  - block:
    #allow 547/udp
    - name: FIREWALLD - DHCPv6 Server - allow 547/udp
      become: true
      ansible.posix.firewalld:
        port: "547/udp"
        permanent: true
        state: enabled
      when: ipv6|bool is true

    #reload
    - name: FIREWALLD - reloaded
      become: true
      ansible.builtin.service:
        service:
          name: firewalld
          state: reloaded        

  when: ansible_os_family == 'RedHat'