---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0

# tasks file for packages_ufw

# Install Firewall - UFW

# Debian
- block:
  #sudo apt-get update
  - name: APT - Update
    become: true
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 86400 #One day
  
  #sudo apt-get -y install ufw iptables
  - name: APT - install ufw iptables
    become: true
    apt:
      pkg: 
        - iptables
        - ufw
      state: present
    register: ufw_installed

  #when installed
  - block:
    #sudo systemctl enable --now ufw
    - name: SERVICE - Ensure ufw service enabled
      become: true
      service:
        name: ufw
        enabled: yes
      register: ufw_enabled

    #sudo systemctl start ufw
    - name: SERVICE - Ensure ufw service started
      become: true
      service:
        name: ufw
        state: started
      when: ufw_enabled
    when: uwf_installed is defined

  when: ansible_os_family == 'Debian'

# RedHat
- block:
  #use firewalld

  - name: "UFW - Not implemented - use firewalld instead"
    debug:  
      msg: "Not implemented for RedHat"

  when: ansible_os_family == 'RedHat'
