---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0

# tasks file for packages_ufw

# Install Firewall - UFW

# Debian
- block:
  #sudo apt-get update
  - name: APT - Update
    become: true
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 86400 #One day
  
  #sudo apt-get -y install ufw iptables
  - name: APT - install ufw iptables
    apt:
      pkg: 
        - iptables
        - ufw
      state: present
    register: ufw_installed
  when: ansible_os_family == 'Debian'

#when installed
- block:
  #sudo systemctl enable --now ufw
  - name: SERVICE - Ensure ufw service enabled
    service:
      name: ufw
      enabled: yes
    register: ufw_enabled

  #sudo systemctl start ufw
  - name: SERVICE - Ensure ufw service started
    service:
      name: ufw
      state: started
    when: ufw_enabled
  when: uwf_installed is defined
