---
# tasks file for fw_rules_snmp_agent

# Debian
- block:
  #use ufw
  
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    ufw:
      state: enabled
    register: ufw_started

  #sudo ufw allow 161/udp
  - name: "UFW - Allow 161/udp - ufw allow 161/udp"
    ufw:
      rule: allow
      port: '161'
      proto: udp
      comment: 'SNMP'
    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'
