---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_snmp_agent

# Firewall - SNMP agent

# Debian
- block:
  #use ufw
  
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    become: true
    ufw:
      state: enabled
    register: ufw_started

  #sudo ufw allow 161/udp
  - name: "UFW - SNMP Agent - Allow 161/udp - ufw allow 161/udp"
    become: true
    ufw:
      rule: allow
      port: '161'
      proto: udp
      comment: 'SNMP Agent UDP'
    when: ufw_started is succeeded

  #sudo ufw allow 161/tcp
  - name: "UFW - SNMP Agent - Allow 161/tcp - ufw allow 161/tcp"
    become: true
    ufw:
      rule: allow
      port: '161'
      proto: tcp
      comment: 'SNMP Agent TCP'
    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'

# RedHat
- block:
  #use firewalld

  - block:
    #allow 161/udp
    - name: FIREWALLD - SNMP Agent - Allow 161/udp
      become: true
      ansible.posix.firewalld:
        port: 161/udp
        permanent: true
        state: enabled

    #allow 161/tcp
    - name: FIREWALLD - SNMP Agent - Allow 161/tcp
      become: true
      ansible.posix.firewalld:
        port: 161/tcp
        permanent: true
        state: enabled

  - block:
    - name: FIREWALLD - Allow snmp service
      become: true
      ansible.posix.firewalld:
        service: snmp
        permanent: true
        state: enabled

    #reload
    - name: FIREWALLD - reloaded
      become: true
      ansible.builtin.service:
        service:
          name: firewalld
          state: reloaded        

  when: ansible_os_family == 'RedHat'