---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_lxc_lxd

# Firewall - Rules for LXC/LXD
# https://documentation.ubuntu.com/lxd/en/latest/howto/server_configure/

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    ufw:
      state: enabled
    register: ufw_started

  - block:
    #sudo ufw allow 8443/tcp
    - name: "UFW - LXD - Allow 8443/tcp - ufw allow 8443/tcp"
      ufw:
        rule: allow
        port: '8443'
        proto: tcp
        comment: LXD
    when: ufw_started is succeeded
  when: ansible_os_family == 'Debian'
