---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_cockpit

# Firewall - Cockpit (Web UI) rules
# https://cockpit-project.org/

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    become: true
    ufw:
      state: enabled
    register: ufw_started

  - block:
    #sudo ufw allow 9090/tcp
    - name: UFW - Cockpit - ufw allow 9090/tcp
      become: true
      ufw:
        rule: allow
        port: '9090'
        proto: tcp
        comment: Cockpit
    when: ufw_started is succeeded
  when: ansible_os_family == 'Debian'

# RedHat
- block:
  #use firewalld

  - block:
    #allow cockpit service
    - name: FIREWALLD - Cockpit service
      become: true
      ansible.posix.firewalld:
        service: cockpit
        permanent: true
        state: enabled

    #allow 9090/tcp
    - name: FIREWALLD - Cockpit - allow 9090/tcp
      become: true
      ansible.posix.firewalld:
        port: "9090/tcp"
        permanent: true
        state: enabled

    #reload
    - name: FIREWALLD - reloaded
      become: true
      ansible.builtin.service:
        service:
          name: firewalld
          state: reloaded        

  when: ansible_os_family == 'RedHat'
