---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# Firewall - Allow forwarding by default
- hosts: all
  become: true
  collections:
    - fruafr.networking
  roles:
    - fw_rules_forward
