---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# Firewall - Rules for LXC/LXD
# https://documentation.ubuntu.com/lxd/en/latest/howto/server_configure/
- hosts: all
  become: true
  collections:
    - fruafr.networking
  roles:
    - fw_rules_lxd
