---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# display the localhost ip addresses
- hosts: localhost
  tasks:
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
    - debug: var=hostvars[inventory_hostname]['ansible_default_ipv6']['address']