---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# Reset the localhost records in /etc/hosts
- hosts: all
  become: true
  collections:
    - fruafr.linux
  roles:
    - localhost_reset
