---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for hostname_change

- block:
  - name: Set hostname if not specified
    pause:
      prompt: "Enter the new hostname"
    register: hostname_prompt
  - set_fact: 
      hostname : "{{ hostname_prompt.user_input }}"
  when: hostname is not defined

- block:
  - name: Set the FQDN if not specified
    pause:
      prompt: "Enter the new fully-qualified domain name"
    register: fqdn_prompt
  - set_fact: 
      fqdn : "{{ fqdn_prompt.user_input }}"
  when: fqdn is not defined

- block:
  - name: Set the hostname
    become: true
    ansible.builtin.hostname:
      name: "{{ hostname }}"

  - name: Modify the hostname file /etc/hostname
    become: true
    ansible.builtin.template:
      src: "{{ hostname_template }}"
      dest: /etc/hostname
      owner: root
      group: root
      mode: '0644'

  - name: Update the /etc/hosts file for 127.0.1.1 to 127.0.1.1 fqdn hostname
    become: true
    lineinfile:
      path: "/etc/hosts"
      regexp: "127.0.1.1.*"
      line: "127.0.1.1 {{ fqdn }} {{ hostname }}"
      state: present
      backup: yes





