---
# tasks file for fw_rules_strict

# SSH must have been authorized prior

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    ufw:
      state: enabled
    register: ufw_started

  - block:

    #sudo ufw deny incoming
    - name: UFW - ufw deny incoming
      ufw:
        direction: incoming
        proto: any
        policy: deny

    #sudo ufw allow outgoing
    - name: UFW - ufw allow outgoing
      ufw:
        direction: outgoing
        proto: any
        policy: allow

    #sudo ufw allow in on lo
    - name: UFW - Allow incoming localhost - ufw allow in on lo
      ufw:
        direction: incoming
        proto: any
        policy: allow
        interface: lo

    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'
