---
# tasks file for fw_rules_strict

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    ufw:
      state: enabled
    register: ufw_started

  - block:
    #sudo ufw allow ssh
    - name: UFW - SSH - ufw allow ssh
      ufw:
        rule: allow
        name: OpenSSH

    #sudo ufw deny incoming
    - name: UFW - ufw deny incoming
      ufw:
        direction: incoming
        proto: any
        policy: deny

    #sudo ufw allow outgoing
    - name: UFW - ufw allow outgoing
      ufw:
        direction: outgoing
        proto: any
        policy: allow

    #sudo ufw allow in on lo
    - name: UFW - Allow incoming localhost - ufw allow in on lo
      ufw:
        direction: incoming
        proto: any
        policy: allow
        interface: lo

    when: ufw_started is succeeded

  #To check status of UFW
  #sudo ufw status
  #sudo ufw status verbose
  when: ansible_os_family == 'Debian'
