---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_strict

# Firewall - Strict rules

# SSH must have been authorized prior else your SSH connections will be impossible.

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    become: true
    ufw:
      state: enabled
    register: ufw_started

  - block:

    #sudo ufw deny incoming
    - name: UFW - ufw deny incoming
      become: true
      ufw:
        direction: incoming
        proto: any
        policy: deny

    #sudo ufw allow outgoing
    - name: UFW - ufw allow outgoing
      become: true
      ufw:
        direction: outgoing
        proto: any
        policy: allow

    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'

# RedHat
- block:
  #use firewalld

  - name: "Strict rules - Not implemented"
    debug:  
      msg: "Not implemented for RedHat"

  when: ansible_os_family == 'RedHat'