---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for ping_host_multi

# ping multiple hosts

- name: Ping the hosts
  shell: "{{ ping_command }} {{ item }}"
  loop: "{{ targets }}"
  register: command_output
  ignore_errors: yes
  no_log: true
  changed_when: false

- name: Ping Successes
  debug:
    msg: "PING SUCCESS"
  when: item.rc == 0
  loop: "{{ command_output.results }}"
  loop_control:
    label: "Ping {{ item.item }}"


