---
# (c) Copyright: David HEURTEVENT, 2023
# License: GPL 3.0
# tasks file for fw_rules_dhcp_client

# Firewall - DHCP Client rules

# Debian
- block:
  #use ufw
  #sudo ufw enable
  - name: UFW - Ensure UFW is enabled
    become: true
    ufw:
      state: enabled
    register: ufw_started

  - block:
    #sudo ufw allow 68
    - name: UFW - DHCP - ufw allow 68
      become: true
      ufw:
        rule: allow
        port: '68'
        proto: udp
        comment: 'DHCP Client'
      when: ipv4|bool is true

    #sudo ufw allow 546
    - name: UFW - DHCPv6 - ufw allow 546
      become: true
      ufw:
        rule: allow
        port: '546'
        proto: udp
        comment: 'DHCPv6 Client'
      when: ipv6|bool is true

    when: ufw_started is succeeded

  when: ansible_os_family == 'Debian'

# RedHat
- block:
  #use firewalld

  - block:
    #allow 68/udp
    - name: FIREWALLD - DHCP Client - allow 68/udp
      become: true
      ansible.posix.firewalld:
        port: "68/udp"
        permanent: true
        state: enabled
      when: ipv4 |bool is true

    #allow 546/udp
    - name: FIREWALLD - DHCPv6 Client - allow 546/udp
      become: true
      ansible.posix.firewalld:
        port: "546/udp"
        permanent: true
        state: enabled
      when: ipv6|bool is true

    #reload
    - name: FIREWALLD - reloaded
      become: true
      ansible.builtin.service:
        service:
          name: firewalld
          state: reloaded        

  when: ansible_os_family == 'RedHat'